# Generated by Django 5.1.2 on 2024-11-18 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('gmail', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a valid Gmail address', regex='^[a-zA-Z0-9._%+-]+@gmail\\.com$')])),
            ],
        ),
    ]
