# Generated by Django 5.1.2 on 2024-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_msg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessage',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
