# Generated by Django 5.1.2 on 2024-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_gmail', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('join_url', models.URLField(blank=True, max_length=500, null=True)),
                ('meeting_passed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', 'time'],
            },
        ),
    ]
