# Generated by Django 5.1.2 on 2024-12-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoommeetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoommeeting',
            options={'ordering': ['-admin_meeting_time']},
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='time',
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='admin_meeting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='utc_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
