# Generated by Django 5.1.2 on 2024-11-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('project_picture', models.ImageField(upload_to='project_pictures/')),
                ('completed', models.BooleanField(default=False)),
                ('project_info', models.TextField()),
                ('time_to_complete', models.DurationField(help_text='Format: days, hours, minutes')),
            ],
        ),
    ]
