# Generated by Django 5.1.2 on 2024-12-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_projects', '0002_alter_clientproject_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='time_to_complete',
            field=models.IntegerField(),
        ),
    ]
