# Generated by Django 5.1.2 on 2024-12-23 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_projects', '0003_alter_clientproject_time_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
