# Generated by Django 5.1.2 on 2024-12-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuseradmin',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
